### ISSUE TITLE
Are there best-practices crypto settings available?

### ISSUE THREAD

**Issue by law** [coturn/coturn#110]
Given the prevalence of various organizations surreptitiously listening in to folks' calls worldwide, would it be possible to recommend a preferred, 'high security', configuration for Coturn, a la https://cipherli.st/ ?

**Comment by saphsoph88** [comment]
Hi @law ,

Did you manage to get any solid feedback here. I'm in installation phase and I want to achieve your goals.

Thanks

**Comment by shadoxx** [comment]
As a general rule, TLS 1.0, 1.1, and 1.2 should be avoided as of the posting of this comment, as well as all versions of SSL.
When setting up web servers, I use the Mozilla SSL Configuration Generator: https://mozilla.github.io/server-side-tls/ssl-config-generator/

As of the posting of this comment, the recommended cipher suites from Mozilla are:
ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS

I personally disable the CBC cipher suites because of how they operate, but they are recommended for compatibility reasons for older devices. I would take an assessment of your environment, see what cipher suites all expected devices support, and go from there. Hope this helps!

**Comment by misi** [comment]
I have added a PR to cipherli.st. https://github.com/RaymiiOrg/cipherli.st/pull/110
Any comment warmly welcomed!

**Comment by eakraly** [comment]
Unless there are objections closing this issue.
TLS configuration for turnserver is not different from TLS configuration for any other server and also very much use dependent (some run on old servers or old versions of openssl, have custom requirements for cyphers etc)
