### ISSUE TITLE
Coturn performance testing

### ISSUE THREAD

**Issue by ShruthiRaj174** [coturn/coturn#1147]
We are trying to do performance testing on coturn , so want some suggestions on tolls we can use for testing

**Comment by eakraly** [comment]
Hi @ShruthiRaj174 

It is not clear what is the question - could you be more specific?

**Comment by ShruthiRaj174** [comment]
Hi @eakraly 

We are trying to do performance testing on coturn , using selenium .Since selenium is taking more time to test , want some suggestions if any tools we can use for doing performance testing on coturn target is test for 500 users .

**Comment by eakraly** [comment]
Performance numbers depend on use case and hardware that you use
You can do perf test using `turnutils_uclient` (instead of selenium) to simulate clients sending/receiving traffic

I cannot give you numbers because they are only meaningful in a context: what is your app, how much data does it send and receive, what are size of the packets, do you test STUN or TURN or both, etc...

**Comment by ShruthiRaj174** [comment]
Hi Eakraly,

Currently started with selenium , since we have some constraints on initiating calls we used selenium . So want some inputs to do performance testing using selenium .
