### ISSUE TITLE
Coturn doesn't start (Address in use)

### ISSUE THREAD

**Issue by seekbat** [coturn/coturn#1206]
HI
I tried to install coturn on a clean ubuntu installation with apt install

I never get it running.

In the logs I got the following error.
```
0: : Trying to bind fd 12 to <127.0.0.1:3478>: errno=98
Cannot bind local socket to addr: Address already in use
0: : Cannot bind TLS/TCP listener socket to addr 127.0.0.1:3478
0: : Trying to bind TLS/TCP listener socket to addr 127.0.0.1:3478, again...
```
but when i check the port assignement it is assigned  to the turn server
```
turnserve 78688      turnserver   13u  IPv4 375726      0t0  TCP 127.0.0.1:3478 (LISTEN)
turnserve 78688      turnserver   15u  IPv4 375728      0t0  TCP 127.0.0.1:3479 (LISTEN)
```
I tried to set the ip of the server in the config file but I get the same error but only whit the Network IP

**Comment by seekbat** [comment]
i followed the following tutorial: https://gabrieltanner.org/blog/turn-server/ 
but no success still the same problem and if I change the port I get the same error with the new port

**Comment by JeanPluzo** [comment]
Hi seekbat,
it seems you're kind of ok in your config file. I'm going to assume this is the case.
- Have you checked that no other program/process is already using port 3478 before you start coturn?
- Are you running coturn with sudo rights?
- Do you have more than one network interface?
- If you get the above error, but the port assignment is successful, have you tried testing your turn/stun server (Trickle ICE)?
- You seem to be binding to localhost (127.0.0.1). Is there a specific reason for this?

Regards,
J.

**Comment by seekbat** [comment]
Hi Jean

1. no, there is nothing on the server besides Coturn. Same Error happens with every port I change it to.
In the logs the error above repeats to doom.
2. im logged in as root
3. no just one
4. yes error 701
5. that was default, i changed it to 0.0.0.0 and once to the public IP as the server is hosted publicly but no change

**Comment by JeanPluzo** [comment]
Hi again,
- which version of coturn are you using?
- are you using docker or systemd?
- if it's systemd, could you post the unit file? I had problems regarding port binding and it was because of the way the unit file is configured
- are you using TLS (certificates)?

Regards,
J.

**Comment by seekbat** [comment]
1. its 4.5.2
2. it's systemd
3. yes
```
[Unit]
Description=coTURN STUN/TURN Server
Documentation=man:coturn(1) man:turnadmin(1) man:turnserver(1)
After=network.target

[Service]
User=turnserver
Group=turnserver
Type=notify
ExecStart=/usr/bin/turnserver -c /etc/turnserver.conf --pidfile=
Restart=on-failure
InaccessibleDirectories=/home
PrivateTmp=yes
AmbientCapabilities=CAP_NET_BIND_SERVICE #added this as it was the solution for a similar problem

[Install]
WantedBy=multi-user.target

```
4. no, not yet

**Comment by JeanPluzo** [comment]
So, if I remember correctly, I had to make an override file in `/etc/systemd/system/coturn.service.d/override.conf`. This file contains the following:

`[Service]`
`LimitNOFILE=1048576`
`AmbientCapabilities=CAP_NET_BIND_SERVICE`
`ExecStart=`
`ExecStart=/usr/bin/turnserver -c /etc/turnserver.conf --pidfile /var/tmp/turnserver.pid --no-stdout-log --simple-log --log-file /var/log/turnserver/turnserver.log`
`Restart=always`

Your already have the `AmbientCapabilities`. 
Can't really remember where I found the double `ExecStart`, but this works for me. Perhaps in the new 2.6 version this has been improved.
Also, since you already have coturn as a unit, it starts immediately on system startup. It just needs the network service (`After=network.target`). I guess you've been trying to start coturn on your own. This was a problem for me too, since coturn had already started and I was starting it a second time during my tests. This could be the reason you're getting the `Cannot bind` error. Perhaps disable coturn as a unit, restart the system and try to start it yourself with command line parameters.

Regards,
J.

**Comment by JeanPluzo** [comment]
So, if I remember correctly, I had to make an override file in `/etc/systemd/system/coturn.service.d/override.conf`. This file contains the following:

`[Service]`
`LimitNOFILE=1048576`
`AmbientCapabilities=CAP_NET_BIND_SERVICE`
`ExecStart=`
`ExecStart=/usr/bin/turnserver -c /etc/turnserver.conf --pidfile /var/tmp/turnserver.pid --no-stdout-log --simple-log --log-file /var/log/turnserver/turnserver.log`
`Restart=always`

Your already have the `AmbientCapabilities`. 
Can't really remember where I found the double `ExecStart`, but this works for me. Perhaps in the new 2.6 version this has been improved.
Also, since you already have coturn as a unit, it starts immediately on system startup. It just needs the network service (`After=network.target`). I guess you've been trying to start coturn on your own. This was a problem for me too, since coturn had already started and I was starting it a second time during my tests. This could be the reason you're getting the `Cannot bind` error. Perhaps disable coturn as a unit, restart the system and try to start it yourself with command line parameters.

Regards,
J.

**Comment by seekbat** [comment]
on what os/linux are you running it?
i got no change with that and when I restart the server and directly check the logs I'm still on the same error.

**Comment by seekbat** [comment]
this is the configuration I had to censor some infos in {}
```
# TURN server name and realm
realm={domain}
server-name=turnserver

listening-ip=0.0.0.0

# External IP-Address of the TURN server
external-ip={servers address}

# Main listening port
listening-port=35012

# Further ports that are open for communication
min-port=10000
max-port=20000


# Use fingerprint in TURN message
fingerprint

# Log file path
log-file=/var/log/turnserver.log

# Enable verbose logging
verbose


# Specify the user for the TURN authentification
user={user:password}

# Enable long-term credential mechanism
lt-cred-mech

```

**Comment by JeanPluzo** [comment]
I don't see a `relay-ip` setting in your config file.
That's the only thing that I would try.
Other than that, perhaps it's best to use the new 4.6 version.
Lots of luck!

Regards,
J.
