### ISSUE TITLE
What is role of XOR-RELAYED-ADDRESS ?

### ISSUE THREAD

**Issue by nowjean** [coturn/coturn#1214]
Hi
I am running coturn behind NAT and I captured TURN traffic with wireshark.
My coturn's In-bound and Out-bound IP is diffrent. 
Please refer to another issue [https://github.com/coturn/coturn/issues/1210]

My coturn returend XOR-RELAYED-ADDRESS(NAT IP) to client but, client does not use XOR-RELAYED-ADDRESS. Client only communicate with XOR-PEER-ADDRESS or coturn Public IP.

Turn and streaming working correctly. 
What is role of  XOR-RELAYED-ADDRESS? Is it not using on TURN traffic between client and coturn?

```
345	11.186109	<Coturn Inbound IP>	<ClientIP>	STUN	150	Allocate Success Response XOR-RELAYED-ADDRESS: <NAT-IP>:49153 XOR-MAPPED-ADDRESS: <ClientIP>:56789 lifetime: 600
365	11.323736	<ClientIP>	<Coturn Inboud IP>	STUN	166	Channel-Bind Request ChannelNumber=0x4000 XOR-PEER-ADDRESS: 10.0.44.33:40420 user: test realm: test with nonce
369	11.340880	<Coturn Inboud IP>	<ClientIP>	STUN	827	ChannelData TURN Message
```

**Comment by rolandwu777** [comment]
@nowjean  Recently, I am trying to see if I can use coturn as a relay to bridge between internet and a private network which has no public ip address, so I am thinking the behaviors on these ice/turn and I think I gained a little bit insight.

For your question, I don't have your topology and ice candidates, so I may not be able to pin point your issue. However, during the ice, you are going to have mulitple candidates and mulitple paths. Later it will decide a better path to send and receive messages. If one of xor-relayed-addressed become invalid (due to a bug), that may still work. It will use other paths, as long as it can reach the other endpoint.

For example, the turn server sends a stun message on behalf of the client, but for some reason turn server's xor-relay-addresss is not right (due to a bug?), and that might still work. As long as the other end point can receive the message, it can just reply to where it sent from. Thus it can estalbish a path. 

On the other hand, if the xor-relay-address is correct, it could provide an additional path. This is a line of thought I can assist you with.

**Comment by rolandwu777** [comment]
@nowjean  The other direction you can think is when your client has the turn server's credential, turnserver become the an extension of the client. It will return you turn server's public address and port for this session you can use as an ice candidate. Then you send that candidate to the other client through SIP or other protocol. The other client can use STUN to estalbish a possible path throught that candidate.

**Comment by eakraly** [comment]
@nowjean 
XOR-RELAYED-ADDRESS is the address that TURN server associates with the client - and this is the address that client will send to the peer as a candindate (relay). 
So XOR-RELAYED-ADDRESS is for the peer, not for the client.
Client will continue communicating with TURN which will forward the data to peer through XOR-RELAYED-ADDRESS.
