### ISSUE TITLE
Support for multiple realms?

### ISSUE THREAD

**Issue by PeuKaa** [coturn/coturn#126]
Is it possible to configure coturn accept users in multiple realms?
I can sure add several users for different realms, but when testing, only the users in current default realm (defined in configuration settings) are accepted.

**Comment by misi** [comment]
Hi,

Unfortunately Origin draft is dead.
So i think there is no way actually to have multi realm. Only way to deploy
multiple coturn instances for multi realm.

(I have an idea how to use multi realm with one instance, and signal from
client side wich realm the actual user belongs to, but it is not yet
 started to standardize/validate it within IETF TRAM WG).

Misi


2017. máj. 10. 8:07 ezt írta ("peuris" <notifications@github.com>):

Is it possible to configure coturn accept users in multiple realms?
I can sure add several users for different realms, but when testing, only
the users in current default realm (defined in configuration settings) is
accepted.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/coturn/coturn/issues/126>, or mute the thread
