### ISSUE TITLE
[Question] What usage of SQLite DB

### ISSUE THREAD

**Issue by nowjean** [coturn/coturn#1270]
Hi All.

I've read this wiki (https://github.com/coturn/coturn/wiki/CoturnConfig). But I don't understand of necessity of SQLite DB.

Is it only for credential security? 
or Can it be affect on performance of coturn? (e.g. save realm and caching something..)

**Comment by JeanPluzo** [comment]
Hi,

AFAIK the SQLite DB is only there for credentials. Perhaps you want only specific users to connect to coturn, but since you have many (i.e. more than 10) it could get problematic to manage all users. By using a DB you can manage your users.
Take a look inside the `turnserver.conf` file. There's a better explanation there.
This is also mentioned in the main coturn README: "User databases (for user repository, with passwords or keys, if authentication is required)"

Regards,
J.
