### ISSUE TITLE
A confuse about "stun_make_type" function

### ISSUE THREAD

**Issue by xmanmax** [coturn/coturn#187]
Hi，I read coturn src codes and found a method as below, it confused me ,what it used for?
u16bits stun_make_type(u16bits method) {
  method = method & 0x0FFF;
  return ((method & 0x000F) | ((method & 0x0070)<<1) | 
	  ((method & 0x0380)<<2) | ((method & 0x0C00)<<2));
}
T&R

**Comment by misi** [comment]
Hi,

AFIAU

https://tools.ietf.org/html/rfc5389
```
                        0                 1
                        2  3  4 5 6 7 8 9 0 1 2 3 4 5

                       +--+--+-+-+-+-+-+-+-+-+-+-+-+-+
                       |M |M |M|M|M|C|M|M|M|C|M|M|M|M|
                       |11|10|9|8|7|1|6|5|4|0|3|2|1|0|
                       +--+--+-+-+-+-+-+-+-+-+-+-+-+-+
                Figure 3: Format of STUN Message Type Field

   Here the bits in the message type field are shown as most significant
   (M11) through least significant (M0).  M11 through M0 represent a 12-
   bit encoding of the method.  C1 and C0 represent a 2-bit encoding of
   the class.  A class of 0b00 is a request, a class of 0b01 is an
   indication, a class of 0b10 is a success response, and a class of
   0b11 is an error response.
```


// This line clears the 4 most significant bit(MSB), because method ID is 12 bit long. M0..M11
// So clears with 0 the 4 MSB from 16bit unsigned
method = method & 0x0FFF; 


return ((method & 0x000F) | ((method & 0x0070)<<1) |
((method & 0x0380)<<2) | ((method & 0x0C00)<<2));

0x000F = 0b0000000000001111
0x0070 = 0b0000000001110000
0x0380 = 0b0000001110000000
0x0c00 = 0b0000110000000000

After it make space for the C0 and C1 bit "class bits" according rfc terminology.
So leave the last 4 bits  where they are 
The 3 bits moved and shifted 1 bit left
And the two others moved 2 bits left.

At the end it is compositing with OR  back the full "Message Type" in format above.

At least I understand it this way. ( I hope I didn't miss lead you with my explanation. :) )

Please close the issue if you think I have addressed your question

BR,
Misi

**Comment by misi** [comment]
Please reopen it if you have any further comments..
