### ISSUE TITLE
Switch from Autotools to Cmake

### ISSUE THREAD

**Issue by RanjKuru** [coturn/coturn#211]
It would be nice if somebody would help to switch to CMake.

**Comment by firegurafiku** [comment]
@RanjKuru 
Are there official plans to switch to CMake or that's just your personal wishlist item?

**Comment by misi** [comment]
Please send Pull Requests.. :-)

**Comment by LorbusChris** [comment]
I'm interested in this as well in order to simplify my RPM spec for Fedora builds.
@RanjKuru have you done some work on this already? I'd happily review/finish a PR :)

**Comment by LorbusChris** [comment]
This should include/fix:
- setting capabilities on dirs and files (and adding a --no-setcap build flag to disable this behaviour)
- fixing duplicate build IDs on turnserver and turnadmin

**Comment by firegurafiku** [comment]
Okay, I'm ready to tackle this issue if nobody has already done significant progress. I also want to make use of [`FindPkgConfig.cmake`][1] for dependency resolution (see related issue #152). Any objections?

[1]: https://cmake.org/cmake/help/v3.0/module/FindPkgConfig.html

**Comment by firegurafiku** [comment]
@LorbusChris 

Can you please explain what are the issues with capabilities and build IDs? How should CMake behave to deal with them properly?

**Comment by LorbusChris** [comment]
@firegurafiku 
Here's the build log from my latest rpm build:
https://copr-be.cloud.fedoraproject.org/results/lorbus/coturn/fedora-27-x86_64/00722257-coturn/builder-live.log

I'm not sure what needs to change in order to deal with the duplicate build ids warning.

There are also multiple build warnings: 
[-Wimplicit-fallthrough=]
[-Wformat-truncation=]
[-Wstrict-prototypes]

In RPM lint there is an error which probably needs to be fixed/added in the code in this repo:
```
coturn.x86_64: E: missing-call-to-setgroups-before-setuid /usr/bin/turnadmin
coturn.x86_64: E: missing-call-to-setgroups-before-setuid /usr/bin/turnserver
```

Regarding the permission attributes on the files, I currently have to do that in the spec:
https://github.com/LorbusChris/coturn-rpm/blob/master/coturn.spec#L173

It would be nice to have a flag that optionally adds these during build, like e.g. here:
https://github.com/LibreOffice/online/blob/master/Makefile.am#L316 (also take a look at the configure file). I'd say this is not a requirement and could rather easily be added later.

see also: https://github.com/LorbusChris/coturn-rpm/issues/3

**Comment by firegurafiku** [comment]
@misi 
@LorbusChris 

Could you please create a topic branch for the issue? I feel uncomfortable about pull-requesting my commits (which may require additional discussion) right into master. Something like `migrating-to-cmake` would be okay, IMO.

**Comment by firegurafiku** [comment]
@misi 
@LorbusChris 

Guys? If no one of you can create branches in the repo, could you please tell me who is the project's current maintainer?

**Comment by LorbusChris** [comment]
@mom040267 ^
@firegurafiku otherwise just dev on your fork and open a catch-all PR for that branch in this repo?

**Comment by firegurafiku** [comment]
@LorbusChris 

> Otherwise just dev on your fork and open a catch-all PR for that branch in this repo?

Switching to CMake and removing existing scripts will break existing packaging scripts, so it may be a good idea to delay it until the next release. However, I don't feel that my solution is release-ready, so I want to have some prior discussion.

The code I'm about to pull-request currently lays in my fork. If you're interested enough, you may have a look at it here:
https://github.com/firegurafiku/coturn-fork/tree/migrate-to-cmake

**Comment by misi** [comment]
I think we can create a feature branch if you still want to do it.
Sorry for my delayed reply.  @firegurafiku

**Comment by misi** [comment]
I have copy-d your branch as a feature branch. Sorry again for the delay..

**Comment by firegurafiku** [comment]
@misi 

Oh, thank you. However, just creating a branch would be enough. My original intention was to create a PR for extended discussion and code review if necessary. But if the code looks fine to you, I'm fine you have just pulled it in.

**Comment by LorbusChris** [comment]
@firegurafiku 
https://github.com/coturn/coturn/blob/master/Makefile.in#L81 is the reason for the duplicate build-ids. So its not a real issue.

**Comment by KangLin** [comment]
See: #721

**Comment by eakraly** [comment]
There is a working support for cmake
Closing this issue
