### ISSUE TITLE
TLS/TCP socket buffer operation error (callback) via Safari

### ISSUE THREAD

**Issue by KnuX** [coturn/coturn#240]
Hi,

I can't make Safari working with our coturn 4.5.0.7 on Ubuntu Xenial using TLS. It's OK using Chrome and Firefox but not Safari (Mac & iOS).

I also tried via this tool https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ and no error is displayed in Safari's console. In my application, I only get an iceconnectionchangestate to "failed".

But the server is logging this line when its occurs:
> Apr 25 12:01:23 coturn01 turnserver: 4749039: IPv4. tcp or tls connected to: 193.93.127.141:53874
> Apr 25 12:01:23 coturn01 turnserver: 4749039: session 000000000000012676: TLS/TCP socket disconnected: 193.93.127.141:53874
> Apr 25 12:01:23 coturn01 turnserver: 4749039: session 000000000000012676: closed (2nd stage), user <> realm <skyrock.net> origin <>, local 193.93.124.120:5349, remote 193.93.127.141:53874, reason: TLS/TCP socket buffer operation error (callback)

The only workaround I found is to declare iceServers without TLS ("turn:" instead of "turns")...

> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04.3 LTS
> Release:	16.04
> Codename:	xenial
> ii  coturn                             4.5.0.7-1ubuntu1+xenial                    amd64        TURN and STUN server for VoIP

**Comment by misi** [comment]
Try to capture packets to see if the server or the client initiates the tear down.
I guess from the logs that Safari is closing the connection.
So you should try to debug on Safari side why it initiates the disconnect.

**Comment by misi** [comment]
Safari may don't trust in letsencrypt.
If things are so, then it does not seems to be coturn issue.. :grinning:

**Comment by KnuX** [comment]
Maybe... However I have no issue to connect to the webadmin through https... That's weird.

**Comment by misi** [comment]
@mom040267 can you help plz?

**Comment by mom040267** [comment]
Seems like Safari uses system-wide keychain, here is a response to a similar question:

https://support.apple.com/kb/ph25443?locale=en_US

**Comment by misi** [comment]
Thanks. It seems a Safari issue please open an issue there. I close it now but please reopen or update this if you still think that it is a coTURN issue.

**Comment by kskewes** [comment]
For anyone finding this issue like me, it appears that:

1. Google publish a `roots.pem` for use in embedded devices/etc "to talk to Google services". It has some other CA's but not all (including those that sign Let's Encrypt - IdenTrust/DST...) and list appears to have shrunk over M## releases.
2. Many random apps on GitHub/etc fetch this `roots.pem` file probably because it's convenient and then use it as source of truth for TLS calls to **anywhere**.
`libwebrtc` the Google led/chromium WebRTC library uses `roots.pem`.
3. Webkit vendors `libwebrtc` and also by default uses bundled `roots.pem` by this [build value](https://github.com/WebKit/webkit/blob/master/Source/ThirdParty/libwebrtc/Source/webrtc/webrtc.gni#L62).
4. There's some code around looking up and importing host OS roots which may/may not be working on Safari

Have asked in the Webkit Slack group about this and if possible to instead supply a larger list, eg: [Mozilla included root certificates](https://wiki.mozilla.org/CA/Included_Certificates)

**Comment by GregOriol** [comment]
It seem that this might be tracked as webkit bug #219274 (https://b.webkit.org/show_bug.cgi?id=219274) and might be a good news as it has just been resolved on 2020-12-10

**Comment by SirCypher** [comment]
While we all wait for an official change/fix there is a sort-of workaround:
Use ZeroSSL instead of LetsEncrypt.

ZeroSSL certificates are signed by a certificate which is also in the webkit CA store. The Element app on Android is now working properly with coturn and TLS on my private server. No more "Unknown CA" error in Wireshark. :)
ZeroSSL is also supported by quiet a few acme clients, so the switch really isn't too hard.
