### ISSUE TITLE
TTL size for the UDP packages

### ISSUE THREAD

**Issue by vol4iniche** [coturn/coturn#241]
When  I use turnutils_uclient for tests I see that some servers have 100% packets lost. 
I used tcpdump and found that TTL size from the server to the client is 23, but between servers we have 24-25 hops. So this is a reason why we have 100% packets lost. 

on the turn server:
```
# tcpdump udp -n -v and dst $client_ip
10:46:55.832768 IP (tos 0x22,ECT(0), ttl 23, id 14458, offset 0, flags [DF], proto UDP (17), length 128)
    local_ip.port > client_ip.port: UDP, length 100

# ping client_ip -t 23
--- ping statistics ---
23 packets transmitted, 0 received, 100% packet loss, time 22175ms

# ping client_ip -t 25
PING client_ip (client_ip) 56(84) bytes of data.
64 bytes from client_ip: icmp_seq=1 ttl=41 time=85.1 ms
64 bytes from client_ip: icmp_seq=2 ttl=41 time=85.3 ms
64 bytes from client_ip: icmp_seq=3 ttl=41 time=85.1 ms
64 bytes from client_ip: icmp_seq=4 ttl=41 time=85.2 ms
^C
--- client_ip ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 85.182/85.231/85.305/0.212 ms
```

Could we manage TTL size? 
Or what the reason to use TTL size 23?

**Comment by misi** [comment]
According https://github.com/coturn/coturn/blob/114881bc9a455b8694634dd4cc3c3acb22845826/STATUS#L27

and so https://tools.ietf.org/html/rfc5766#section-12
```
Time to Live (TTL) field

      Preferred Behavior: If the incoming value is 0, then the drop the
      incoming packet.  Otherwise, set the outgoing Time to Live/Hop
      Count to one less than the incoming value.

      Alternate Behavior: Set the outgoing value to the default for
      outgoing packets.
```
But the ultimate truth is in the source so we need to check it..

The uclient send out all  packets with ttl = 47 not 64!
https://github.com/coturn/coturn/blob/114881bc9a455b8694634dd4cc3c3acb22845826/src/apps/uclient/startuclient.c#L248

My guess that your server is 23 hop away from the server 
and this way because of the Preferred Behaviour 47 - 23 -1 =  23  hop. 
And you see this way 23 hop in the tcpdump.

So everything seems to be correct, the only issue I see that the uclient don't document it's TTL : 47
And also it would be nice to make it configurable... 
If you like then please send a Pull Request with a configurable TTL..

**Comment by vol4iniche** [comment]
Thanks for the explanation!

**Comment by misi** [comment]
Unfortunately I don't know.

**Comment by vol4iniche** [comment]
@misi 
Thanks again!
