### ISSUE TITLE
Official Docker image?

### ISSUE THREAD

**Issue by ErikHellman** [coturn/coturn#273]
I'm finding several Docker images for Coturn available, but it is hard to tell if one is official or at least recommended.

Would it make sense to have a Docker section in the main README that points to official or recommended Docker images? I believe this would greatly improve the adoption of this. 

Thanks!

**Comment by ErikHellman** [comment]
I'd love to help. I'll investigate and see what I can come up with.

**Comment by meteorplus** [comment]
Dockerize it blease!

**Comment by Masterxilo** [comment]
According to

https://hub.docker.com/search/?isAutomated=1&isOfficial=0&page=1&pullCount=0&q=coturn&starCount=0

the current inofficial image with most pulls (by a large margin) is

https://hub.docker.com/r/steppechange/docker-coturn/

maybe one can get inspiration from there or ensure compatibility where it makes sense.

**Comment by misi** [comment]
I think we should make an autobuid dockerfile with two steps, 
 * one that has the build env and the binary 
 * and the second that contains

We should have 3 differently tagged images for for different auth type

* Long Term Credential (username/password)
* Time Limited Long Term Credential (REST/ shared secret)
* OAuth

**Comment by Masterxilo** [comment]
I discovered that this thing is available as an ubuntu package, which simplifies building the container a bit. I am currently using something along these lines

Dockerfile
```
FROM ubuntu

RUN apt update
RUN apt install --assume-yes coturn

EXPOSE 3478/tcp
EXPOSE 3478/udp

# TODO maybe need much more to actually handle calls from this server?!
# --min-port <port> Lower bound of the UDP port range for relay endpoints allocation. Default value is 49152, according to RFC 5766.
# --max-port <port> Upper bound of    the UDP port range for relay endpoints allocation. Default value is 65535, according to RFC 5766.
```

and then I use it as follows for ltc (long term credentials, as required (?) by webrtc):

```bash

docker build -t coturn .

USERNAME="some-username"
PASSWORD="some-password"

docker run -ti --rm --publish 3478:3478/tcp --publish 3478:3478/udp coturn:latest \
    turnserver \
        -n \
        --verbose \
        --lt-cred-mech \
        --user $USERNAME:$PASSWORD \
        --realm someRealm \
        --fingerprint \
        --no-dtls \
        --no-tls \
        --listening-port 3478
```

I think I am missing the ports for relay endpoints allocation because I don't really understand what exactly the whole thing does yet...

**Comment by Masterxilo** [comment]
I think just having one image where one can either start it via commandline or edit the config file would be the most flexible.

In any case, please save us from having to build this thing on our own for every distribution we might want to use. If it runs a Linux kernel, it should be a one line command to download and run this thing (a vision finally realized by docker & dockerhub).

**Comment by misi** [comment]
I would happy to check alpine base too.
make such image type to to make the image tiny as possible.

**Comment by misi** [comment]
According my experience alpine not using glibc, and because glibc is faster little bit, and we miss from alping mongo libs, so I have changed my mind. 
Let's build it on top of Debian stable. 
I have already started to work on it. It is work in progress. 
See it in docker branch..
Any comment or Pull Requests welcomed...

**Comment by verglor** [comment]
Hi @misi, if you can use debian:slim which is just 19MB it is not a big deal not having alpine version.

**Comment by misi** [comment]
I have updated docker branch can you check it and comment?
Thanks..

**Comment by misi** [comment]
See in docker folder the README.docker..

I run into this issue: https://success.docker.com/article/docker-compose-and-docker-run-hang-when-binding-a-large-port-range

So I can't open RTP/RTCP port range in docker for coturn. :(
Any idea howto overcome on this issue is very welcomed..


If turn client will generate traffic then it will open ports. 
So it works somehow, but this is not how I expect it should work.

**Comment by misi** [comment]
Any comment on the docker branch? If not I will merge it soon..
Please give me some feedback.. 
Thanks!

**Comment by Danlock** [comment]
@misi 
The docker branch looks pretty good, here are a few admittedly minor things I noticed:

a comment https://github.com/coturn/coturn/blob/docker/docker/coturn/Dockerfile#L34
where you talk about build dependencies, however at that point in the image, aren't they runtime dependencies?

For all your database images, you are pulling the latest docker image by not specifying a tag. By doing this, are you expecting that coturn will always work with the latest versions of mongodb, redis, mysql and postgres? If not and there is a maximum version I think you should limit the docker images to said version. Of course, if its expected coturn will work with the latest then there is no need to change that at all.

Great work!

**Comment by misi** [comment]
@Danlock 
Thanks for the review!

https://github.com/coturn/coturn/blob/docker/docker/coturn/Dockerfile#L34
Great catch. It was an cut & paste.

Regarding the db images. 
Yes I hope coturn will work, 
but to make sure in longer term you are right it would be better to add later versions.

Thanks!!

**Comment by bmariusz** [comment]
I recommend https://hub.docker.com/r/instrumentisto/coturn which is built on top of `alpine:edge, 21.7MB in total - (https://github.com/instrumentisto/coturn-docker-image/blob/master/Dockerfile). Ot provides `entrypoint` which allows you to put whole configuration with `docker run` and pass ssl certs with `--volume`.

**Comment by kevinhartman** [comment]
@misi, is this already resolved? I see a `docker` folder in the repo root.

It's somewhat unclear how to build it, unfortunately. The instructions mention the need to perform manual steps such as running some copy file script as well as editing `turnserver.cfg` which doesn't seem to exist.

Perhaps an official build of this image could be published to DockerHub along with each version release? Regarding which version of the backing DB, perhaps the image on DockerHub could just use whichever one is best for the majority of cases (assuming you want to keep the image small by baking in only the DB needed).

**Comment by OmegaVVeapon** [comment]
Has this task been abandoned?

For what it's worth, I checked out https://hub.docker.com/r/instrumentisto/coturn as recommended by @mariuszbeltowski and it's very well put together in terms of good Docker practices.

Maybe those changes could be pulled into this repo?

**Comment by tyranron** [comment]
I'm a main maintainer of https://hub.docker.com/r/instrumentisto/coturn Docker image. If @misi, or other contributors don't mind, I'm okay with mergin that here to have an official `coturn/coturn` Docker image for community. Also, I may offer my resources to support it and keep-up-to-date (though, that wouldn't require much at all).

**Comment by misi** [comment]
Sorry I was busy I missed out new comments on this issue. 
@tyranron let's meet and discuss how to make it. 
I am happy and fully support to make an official cotrun/coturn docker image even more we can make a help chart too..

**Comment by tyranron** [comment]
@misi nice! Well then, this is how I see the stuff here...


### What should be supported?

- Build image directly from repo's codebase.
- `edge` image versions built from latest `master`.
- `alpine` and `debian` (based on `debian:slim`) image versions built from release tags.
- [Multiarch support](https://github.com/instrumentisto/coturn-docker-image/issues/24) on the same image tag.
- [Basic image tests](https://github.com/instrumentisto/coturn-docker-image/blob/4.5.1.2/test/suite.bats#L23-L119).


### How this can be accomplished?


#### DockerHub automated build

##### Pros
- 👍 No need to poke with secrets manually. Just specify GitHub repo as source for automated builds on DockerHub, and it will do all the stuff about interperabilty between GitHub and itself.
- 👍 Better info about the image on DockerHub. Automated builds add ["Builds"](https://hub.docker.com/r/instrumentisto/coturn/builds) and ["Dockerfile"](https://hub.docker.com/r/instrumentisto/coturn/dockerfile) pages and link to source GitHub repository on image's page. This provides much better user experience.
- 👍 Description on DockerHub is automatically consumed from `README.md`, so properly configured let us to not worry about outdated decriptions.

##### Cons
- 👎 Requires to split repository configuration betwee GitHub and DockerHub. One piece (CI pipelines, releases anf GitHub workflows) is part of GitHub repo, and another piece (automated build rules) will reside in DockerHub settings. While DockerHub settings are pretty trivial, there are still situations when you forget to update DockerHub settings (which isn't a big problem, but is not very pleasant).
- 👎 Image builds on DockerHub are [considered extemely slow](https://github.com/instrumentisto/coturn-docker-image/issues/24#issuecomment-619456901) by many users. Building image with TravisCI or GitHub Actions is much more faster. This is notable if time-to-published-image-after-release is an important concern.
- 👎 DockerHub [doesn't provide obvious and trivial ways](https://github.com/docker/hub-feedback/issues/1874) for multiarch support for its automated builds. To support multiarch builds some [untrivial `hooks` magic](https://github.com/jmb12686/go-loadtest-api/tree/master/hooks) is required at the moment.
- 👎 To test Docker image we still need to run some CI pipeline (so x2 builds, and we test the image not being published, despite the reproducability). And we cannot reject image publishing if tests do not pass.


#### TravisCI/GitHub Actions build

##### Pros
- 👍 Faster builds than on DockerHub. Properly set up pipelime may even publish Docker images before the GitHub release is published.
- 👍 Obvious and trivial integration with [Docker `buildx`](https://github.com/docker/buildx) for multiarch builds.
- 👍 We can test the image being built before it's going to be published on DockerHub.

##### Cons
- 👎 Worse info about image on DockerHub image's page. There is no link to source repository, so we should care to put it in description manually. There is no actual `Dockerfile`, so we should care to link it in description manually (which is not big convern as will be done anyway).
- 👎 No image description auto-updates. Either we do it manually every time, or do some [additional magic in CI pipeline for that](https://github.com/factoriotools/factorio-docker/blob/994a091595b35a36e1d277c741eed342aea93781/.travis.yml#L34).
- 👎 We should manually manage secrets to access DockerHub with `write` priveleges on CI pipeline.

-------------------------------------

Despite the testability and some untrivial stuff, I'm still in favor of DockerHub automated build, because I think better user experience is more valuable than inner toolchain weirdness.

But I'm totally OK to go with CI pipeline way if maintainers prefer that one.

-------------------------------------

Once we have some agreement on this question, I'll describe the repository layout  possible changes to accomplish the chosen variant.

**Comment by killua99** [comment]
To extend @tyranron comment, could be good to take a look at: https://docs.docker.com/docker-hub/official_images/

And evaluate if this repo could be part of Official Docker Images, that could be the best case scenario aiming for an official badge.

On Freenode IRC we could find more info about it and how to submit a proposal.

**Comment by misi** [comment]
First lets create an image coturn/coturn.
I created an organization coturn. @tyranron,  please provide me your docker hub account.

**Comment by tyranron** [comment]
@misi it's just the same: [@tyranron](https://hub.docker.com/u/tyranron)

**Comment by x5engine** [comment]
@tyranron I say 👍👍👍👍 and 👍

**Comment by tankakatan** [comment]
Hi all. Hope everyone in this thread is well!

@misi, @tyranron if possible, could you guys please post any updates on the official **coturn** docker image?

**Comment by tyranron** [comment]
@tankakatan sorry, but I had no time to dedicate to this recently. I'll try to make some during next month.

**Comment by corytheboyd** [comment]
Thanks for taking this on @tyranron and @misi! Will be following along. Do you anticipate much changing from https://github.com/instrumentisto/coturn-docker-image with this new image?

**Comment by tyranron** [comment]
@corytheboyd nope, but we're going to support ARM builds definitely.

**Comment by misi** [comment]
@tyranron let me know if we can meet and discuss further howto build the image. until it I will run an automated image build on dockerhub coturn/coturn

**Comment by tyranron** [comment]
@misi I've recently [done some job](https://github.com/instrumentisto/haraka-docker-image/) on a new toolchain for building multi-arch Docker images via GitHub Actions and pushing them to ghcr.io, DockerHub, and quay.io, with a clever image tagging in mind, and keeping description up-to-date.

Once I find some time, I'll adapt that work to this repo as a PR.

**Comment by bierzorutas** [comment]
Any advance on this ? I can also find some time to help if needed.

kind regards

**Comment by misi** [comment]
@tyranron @bierzorutas Can we make a short call and discuss how to make it happen? 
I saw the github actions. It is very nice and it would be great to have. :)

**Comment by tyranron** [comment]
@misi @bierzorutas please, wait for a PR a little bit more. I almost reached the point of contibution.
