### ISSUE TITLE
The log does not print date and pid info

### ISSUE THREAD

**Issue by chenxinlong** [coturn/coturn#305]
The log output like pics below : 
![image](https://user-images.githubusercontent.com/9261954/48999951-159e9100-f193-11e8-8d5e-ef259a196542.png)

There's no date and pid info found. 

turnserver config as follow : 
```
#no-stdout-log
#log-file=/var/tmp/turn.log
...
log-file=stdout
...
#syslog
#simple-log
```

Supervisor config as follow : 
```
command = /path/to/turnserver -c /etc/turnserver/turnserver.conf -v
...
stdout_logfile = /var/log/supervisor/turnserver.info.log
stdout_logfile_maxbytes = 100MB
stdout_logfile_backups = 5
stderr_logfile = /var/log/supervisor/turnserver
```

I'v tried the -V option, but still doesn't work.  Is there any way to deal with it ? Or  I make a mistake on configuration.

**Comment by misi** [comment]
I need to check it..

**Comment by chenxinlong** [comment]
So normally turnserver's log should be to include the date and pid field ?

**Comment by chenxinlong** [comment]
Is there any progress ?

**Comment by misi** [comment]
Please check the source if you need the answer now.
Sorry I am busy with debian packaging.
I can only answer on next week or so..

**Comment by bradleythughes** [comment]
The turnserver does not prepend the date or pid to its log messages, as you have seen. If you want this, I would recommend enabling the syslog option in your configuration file, since syslog typically adds date, pid, and other info to the log message. Another benefit is that syslog and friends tend to have some sort of log rotation in place.

**Comment by chenxinlong** [comment]
I'm sorry but for some reason, syslog is not a good idea for my current deployment. Have you considered prepend the date or pid to the log messages ?    

I've also tried a workaround which is : prepend date info by using the `ts` command which is a util command included in `moreutils`.  The relevant conf is as follow : 

supervisor conf : 
```
[program:turnserver]
command = /etc/supervisor/conf.d/run-worker.sh "turnserver"
user = root
autostart = true
autorestart = true
stdout_logfile = /var/log/supervisor/turnserver.info.log
stdout_logfile_maxbytes = 100MB
stdout_logfile_backups = 5
stderr_logfile = /var/log/supervisor/turnserver.error.log
```

/etc/supervisor/conf.d/run-worker.sh
```
bash -c 'turnserver -c /etc/turnserver/"$WORKER_NAME".conf -v | ts '[%Y-%m-%d %H:%M:%S]' 
```

This solved the log problem, but after the adjustment, seems the turnserver's normal work is affected. Specifically, when my [web client](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) is unable to receive the relay properly. I think you should be able to reproduce this problem.

I understand that these two things may not be related, but I can reproduce this problem on every one of my turnserver.

**Comment by bradleythughes** [comment]
> Have you considered prepend the date or pid to the log messages ?

No, I don't think anyone has, since the syslog option gives you more flexibility. I am curious why you say you cannot use it?

Regarding your problem with coturn not working when piping output through `ts`, I am not sure what to do about that.

Again, my best suggestion is to use the syslog. If you cannot, it would be helpful to understand why, so that maybe something can be done to make it possible.

Sorry for the late reply, I had missed that you replied to my earlier comment.
