### ISSUE TITLE
Correct type of EC2 in AWS for setting up CoTURN

### ISSUE THREAD

**Issue by Chandramouli-P** [coturn/coturn#323]
Hello,

Can anybody suggest me the exact EC2 type, number of cores, RAM in AWS to setup CoTURN server (for Video conferencing)? I am aware that instances with enhanced networking are preferable. But, there are many instance types are available with enhanced networking. So, I am a bit confusing. Hence, request you to give your valuable recommendations.

Thank you.

Best Regards,
Chandramouli.

**Comment by Chandramouli-P** [comment]
Hello,

Anybody update would be appreciated.

Thank you.

Best Regards,
Chandramouli.

**Comment by misi** [comment]
This is more EC2 specific question than coturn specific. 
Unfortunately I don't know the answer..

**Comment by Chandramouli-P** [comment]
Sure. Let us see if any other people help me in this CoTURN users list. Thank you.

**Comment by bradleythughes** [comment]
There is no right answer here, really, since everyone's needs are different.

As you pointed out, an instance type with Enhanced Networking may be preferable, since you get a higher and more consistent packets-per-second, but Enhanced Networking is by no means a requirement.

From my experience*, instances tend to be network bound before CPU/RAM, meaning that multiple instances of a smaller type worked "best". We started with t2.medium, then moved to c4.large, and last I saw c5.large was the instance type of choice.

One thing to keep in mind: network traffic costs money in AWS ( and any other public cloud from what I've seen), so you may want to find ways to limit the amount of data going through your EC2 instances, for example by reducing the maximum allowed video bitrate when a connection is using TURN. If you are using WebRTC, there are examples on how to do this on the web.

Hope this helps :)

(I am going to close this issue now, since there's not really anything actionable after moving the discussion to the mailing list.)

* At my previous employer, whom I left at the end of May, 2018.
