### ISSUE TITLE
WebRTC Long Time Credentials and Auth Secret

### ISSUE THREAD

**Issue by madmath03** [coturn/coturn#360]
Hello,

The documentation for turnserver says that `--lt-cred-mech` should be used for WebRTC. The same documentation also mentions that `--use-auth-secret` can be used for TURN REST API and is used with long-term credentials mechanism.

Problem: when you enable both long term credentials and authentication secret, the turn server will display a configuration alert:
https://github.com/coturn/coturn/blob/856c3c9ff620ae2b00354ac55c539ba3dadb16f7/src/apps/relay/mainrelay.c#L2238-L2242

So, what's really the proper use for WebRTC usage ? Is it the documentation that should be updated or is it the configuration alert that is not appropriate ?

**Comment by misi** [comment]
Read this first:
https://www.ietf.org/proceedings/87/slides/slides-87-behave-10.pdf

Both auth method could be used. 
- LTC (username/password)
- REST/use-auth-secret in coturn terminology/ 
You can't use both in the same time!!
(Don't be confused that REST is internally depends on LTC. This is the reason for the warning.)

Rest is more secure, because it's secret is time limited, but you need an Server that issues the credential based on the shared secret. This server and API is not available in coturn out of the box. You have to implement it.
(Just as an (not so nice) example my REST API server php code: https://github.com/misi/stun-api/)

So I propose to use --use-auth-secret, but in such case you need to implement on browser side a credential update mechanism too.

The other way is more simple but less secure. (turn credential is revealed and could be easily extracted on browser side from the js code )

**Comment by madmath03** [comment]
Thanks a lot for the explanation. That does make think a bit clearer.

I used Coturn with (Spreed.me)[https://apps.nextcloud.com/apps/spreedme] for a while and I'm now experimenting with (NextCloud Talk)[https://apps.nextcloud.com/apps/spreed] which is based on (simpleWebRTC)[https://simplewebrtc.com/].

Both use a shared secret to connect to a TURN server so I guess they offer the full REST experience you described and LTC is not needed in my case.

I'm wondering though: should the wiki documentation mention that LTC is disabled when auth secret is enabled?

**Comment by misi** [comment]
I think we should document how it works internally and from user usage point of view.. 
(Internally it depends on each other.)
So I agree we need more documentation of this.

**Comment by misi** [comment]
Let's close this and open a new issue to clarify docs about auth methods.

**Comment by madmath03** [comment]
> Let's close this and open a new issue to clarify docs about auth methods.

@misi Done with #364.

**Comment by AlbanDAVID** [comment]
For those a little bit lost (as I was). I wrote this article : https://wiki.lenuagemagique.com/doku.php?id=unable_to_use_lt-cred-mech_webrtc_and_static-auth-secret_restapi_at_the_same_time
