### ISSUE TITLE
Can I get tcp relay candidate from turn server? 

### ISSUE THREAD

**Issue by HenryCui1979** [coturn/coturn#379]
I try to use tcp to transport media between two webrtc client.I can get tcp candidate from turn server,but thers is no tcp relay candidate in the candiate lists.In this case,the two webrct can not call each other.What should I do to use only tcp to transport media?

**Comment by misi** [comment]
Try to use TURN URL with transport set.
e.g.

> turn:example.com:443?transport=tcp

**Comment by vepro-dev** [comment]
This parameter has no effect as far I can see in my tests.

**Comment by misi** [comment]
The TURN url only affects communication on TCP between TURN sever and  TURN client(browser),
but  because web Browsers didn't yet implemented request-transoport ( The attribute REQUESTED-TRANSPORT), so the TURN server and peer (Browser) use UDP.

Open an issue on your browser to support to implement REQUESTED-TRANSPORT TCP to be able the client to allocate a TCP poer on  coTURN server! 
The coTURN server implementation is ready only the browser part is missing.

Or try to use TCP without TURN.
See: ICE-TCP https://tools.ietf.org/html/rfc6544
