### ISSUE TITLE
allocation timeout

### ISSUE THREAD

**Issue by WJdenghuo** [coturn/coturn#401]
IPv4. Local relay addr: 172.21.16.2:61994
1132: session 001000000000000006: new, realm=<62.234.105.58>, username=<cnki>, lifetime=600
1132: session 001000000000000006: realm <62.234.105.58> user <cnki>: incoming packet ALLOCATE processed, success
1142: session 001000000000000006: realm <62.234.105.58> user <cnki>: incoming packet BINDING processed, success
1152: session 001000000000000006: realm <62.234.105.58> user <cnki>: incoming packet BINDING processed, success
1162: session 001000000000000006: realm <62.234.105.58> user <cnki>: incoming packet BINDING processed, success
1163: session 001000000000000006: realm <62.234.105.58> user <cnki>: incoming packet BINDING processed, success
1172: session 001000000000000006: refreshed, realm=<62.234.105.58>, username=<cnki>, lifetime=0
1172: session 001000000000000006: realm <62.234.105.58> user <cnki>: incoming packet REFRESH processed, success
1173: session 001000000000000006: closed (2nd stage), user <cnki> realm <62.234.105.58> origin <>, local 172.21.16.2:3478, remote 118.144.9.232:64170, reason: allocation timeout
1173: session 001000000000000006: delete: realm=<62.234.105.58>, username=<cnki>

**Comment by sinisabrcina** [comment]
Hello, we have the same problem, did you find a solution maybe?

**Comment by baptx** [comment]
I have the same problem when using latest version (4.5.1.1) of Coturn STUN and TURN server, using the Debian package. The WebRTC video chat always works for one minute and then it stops with the same message `lifetime=0` in `/var/log/syslog`. The problem does not happen when using Google STUN server stun.l.google.com:19302 with Viagenie TURN server http://numb.viagenie.ca/.
I noticed in `/etc/turnserver.conf` that the default value of max-allocate-timeout=60 so I tried changing it to max-allocate-timeout=3600 but the problem is still here.
Here are the options enabled in the config file:
`verbose`
`syslog`
`user=username:password`
The options `lt-cred-mech` and `realm` don't change anything so I think we don't need to use them.
The same problem happens with `static-auth-secret` when using temporary credentials.
I am only using 1 IP address and the same one for STUN / TURN, I read using 2 IP addresses is not necessary.
Does someone have an idea why it fails and how to stop the disconnection after one minute?

**Comment by baptx** [comment]
I have a similar problem with an allocation timeout after one minute but I am not sure if it for the same reason: https://github.com/coturn/coturn/issues/457

**Comment by Govind10g** [comment]
I'm also facing the same issue, call disconnected after calling without any communication between users.
Error is reason: allocation timeout. 
However I already defined max-allocate-timeout=4800 sec in turnserver configuration file.  Still getting the same error.

Note :- TURN server is behind the NAT gateway in my case.
Does anyone find the solution of this issue ?

**Comment by ggarber** [comment]
This has been opened for a while and it is not a very specific issue (it can happen for many different reasons mostly around your network configuration) so I think it should be closed.

I'll try to help the last comment in the other issue opened for this.
