### ISSUE TITLE
How can I use coturn on AWS EC2 or GCP VM when client is IPv6?

### ISSUE THREAD

**Issue by DevRockstarZ** [coturn/coturn#564]
Only IPv4 (LTE) can use TURN / STUN server,

but IPv6 (5G) can't use TURN / STUN server.

How can I solve this problem?

Do I have to use load balancer?

I installed coturn on EC2 and VM, but IPv6 user can't access to it.

Please help me...

**Comment by sdjksdafji** [comment]
@DevRockstarZ Hi Patrick, I have the same issue with ipv6 only netowrk (5G), how did you solve the issut?

Thanks in advance

**Comment by DevRockstarZ** [comment]
You can use ipv6 network through AWS ELB.
I used AWS Elastic Load Balancer to use ipv6 network.
I just created AWS EC2 and configure EC2 with ELB.

**Comment by sdjksdafji** [comment]
@DevRockstarZ I suspect the same thing but I have not verified end2end. Have you verified that after adding ipv6 listening, the issue of not connecting under 5G has gone?

**Comment by DevRockstarZ** [comment]
@sdjksdafji I didn't configured ipv6(by VPC) on ELB and EC2.
I tried to configure ipv6, but it occured error.
So I configured default VPC and EC2 and ELB.
And I tried with by 5G device and LTE device, it worked really fine.

**Comment by sdjksdafji** [comment]
@DevRockstarZ Thanks for the information, but I am confused about your description. Did you setup the ipv6 for the coturn server eventually?

I am trying to figure out if the root cause is the ipv6 only network in 5G. My observation is that at least the http request to ipv4 works fine in the ipv6 only (5G) network. 

I did setup the ipv6 on ec2 but I don't have access to the 5G network myself. I am waiting for my colleague to do the test to see if it works.

**Comment by DevRockstarZ** [comment]
@sdjksdafji  I didn't setup ipv6 things on EC2, VPC and ELB.
Just create EC2 and VPC configure ipv4 (not ipv6) and Elastic Load Balancer(ELB) will automatically transform ipv6 to ipv4 and send data to EC2.

**Comment by sdjksdafji** [comment]
@DevRockstarZ Thanks. This makes sense. Glad to hear that the root cause is ipv6.

**Comment by yuanchieh-cheng** [comment]
May I ask how you solve the problem when client is using ipv4 and ipv6 both ?
Could you share your coturn config file ? 

For my understanding, the turn server would assign relay address in IP format, which means the ELB would not handle the IPv6 for turn server because the client would send data to turn server directly through ip.  
Do I misunderstanding something?

**Comment by DevRockstarZ** [comment]
@yuanchieh-cheng 
Can you configure Route 53 too? I used ELB and Route53 both.

**Comment by yuanchieh-cheng** [comment]
@DevRockstarZ 
Yes I can.  
Currently I set the route53 with 
```
turn.my-host.com  A record: instance public ipv4
turn.my-host.com  AAAA record: instance public ipv6
```
Could you please share your infrastructure ?
How do you set up the route 53 / elb / instance? 

Thanks a lot!

**Comment by DevRockstarZ** [comment]
@yuanchieh-cheng 
I just created EC2 instance with IPv4, and do not configure anything about IPv6.
And configure Route53 to your EC2 and domain host.
Connect with your IPv6 devices such as 5G devices.

**Comment by yuanchieh-cheng** [comment]
Thanks for your reply. I will try it.
But you have mentioned ELB above. Is that still needed ?

**Comment by DevRockstarZ** [comment]
@yuanchieh-cheng 
If you have multiple coTURN servers you need ELB.
But you have only one coTURN server, you don't need it.

**Comment by yuanchieh-cheng** [comment]
The solution is not work for me.
My mobile phone is IPv6 only and it cannot connect to IPv4 only relay server.
