### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by ZergOnLinux** [coturn/coturn#570]
Hello,

is there a way to add timestamps in the logging?

Is there a way to just log errors? Or log errors and successful messages in different files?

If there is a way, I haven't found it yet.

Best

**Comment by MichaIng** [comment]
Nope, no logging level/verbosity or differentiation possible for now, at least not via config file or command options.

I was looking for this feature as well since Coturn is very verbose by default. For SDcards and similar such verbose file logging is too much and when switched to `syslog` or `tmpfs` you need to have quite some RAM resources.

Probably not what you want, but on SDcard-based SBCs with limited memory I currently use `-l stdout --no-stdout-log` to mute it completely aside of initial startup messages.
- `-l stdout` is required to disable file logging. Log to STDOUT is done anyway by default, hence `-l stdout` effectively only disables file logging and there is no `none` or similar special name.
- `--no-stdout-log` to disable STDOUT logging as well, which in combination with above disables logging completely.

**Comment by PaulWay** [comment]
I've got a patch for full timestamp logging here:

https://github.com/coturn/coturn/pull/618

**Comment by misi** [comment]
It is merged so it will be released in 4.5.2, but with syslog you can also add timestamp..
