### ISSUE TITLE
No response is sent when request does not have http/1.1 ALPN extension

### ISSUE THREAD

**Issue by paulmenzel** [coturn/coturn#585]
With Coturn 4.5.1.1-1.1 set up in front of a Jitsi installation, no reply is received from the server, when no http/1.1 ALPN extension is sent.

    $ curl --no-alpn https://jitsi.molgen.mpg.de
    curl: (52) Empty reply from server

It works with the ALPN extension.

    $ curl -I https://jitsi.molgen.mpg.de
    HTTP/2 200 
    server: nginx/1.14.2
    date: Thu, 18 Jun 2020 10:52:37 GMT
    content-type: text/html
    vary: Accept-Encoding
    strict-transport-security: max-age=63072000

**Comment by felixdoerre** [comment]
Yes, this is what the jitsi nginx config is set up to do: https://github.com/jitsi/jitsi-meet/blob/47cffeb00ab217fe208cf551adad9dfd2fd362a6/doc/debian/jitsi-meet/jitsi-meet.conf#L16
The problem is, that normal turn clients don't send a ALPN extensions so the only sane configuration is to default to turn. Of course that breaks non-alpn https clients, but that is the trade-off that jitsi makes at this point.

**Comment by paulmenzel** [comment]
Interesting. Thank you for pointing this out.

I still have a couple of questions.

1.  I had the same problem, when Coturn was listening on port 443.
2.  Coturn is configured with `no-tcp`: https://github.com/jitsi/jitsi-meet/blob/47cffeb00ab217fe208cf551adad9dfd2fd362a6/doc/debian/jitsi-meet-turn/turnserver.conf#L10. Is that why no response is sent.
3.  Shouldn’t Coturn proxy the packet back to Nginx anyway?

**Comment by felixdoerre** [comment]
Regarding 1: I assume that you got not response with curl when coturn is on 443 (even with specifying alpn). Yes this is expected. Coturn does not speak the http protocol, only the turn/stun protocol
Regarding 2: the `no-tcp` option does not imply the `no-tls` option. And the TLS sockets are used in this context.
Regarding 3: I am not aware of any coturn mechanism that actively detects http traffic and proxies that somewhere.

Summing it up: That there is not http response sent is the expected behavior of coturn which is not a http server but a stun/turn server.

**Comment by paulmenzel** [comment]
Thank you for you replies. I guess I still do not know how Coturn (or a STUN/TURN server) works. ;-)
