### ISSUE TITLE
socket: Protocol not supported

### ISSUE THREAD

**Issue by zrx1118** [coturn/coturn#757]
I met the same problem for [#722](https://github.com/coturn/coturn/issues/722).

RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.5.2 'dan Eider'
0: : log file opened: /var/log/turn_558165_2021-04-28.log
0: : 
Max number of open files/sockets allowed for this process: 65535
0: : 
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 32500 (approximately)
0: : 

==== Show him the instruments, Practical Frost: ====

0: : TLS supported
0: : DTLS supported
0: : DTLS 1.2 supported
0: : TURN/STUN ALPN supported
0: : Third-party authorization (oAuth) supported
0: : GCM (AEAD) supported
0: : OpenSSL compile-time version: OpenSSL 1.1.1g FIPS  21 Apr 2020 (0x1010107f)
0: : 
0: : SQLite is not supported
0: : Redis is not supported
0: : PostgreSQL is not supported
0: : MySQL is not supported
0: : MongoDB is not supported
0: : 
0: : Default Net Engine version: 3 (UDP thread per CPU core)

=====================================================

0: : Domain name: 
0: : Default realm: stun.www.xxx.com
0: : 
CONFIGURATION ALERT: you specified long-term user accounts, (-u option) 
        but you did not specify the long-term credentials option
        (-a or --lt-cred-mech option).
        I am turning --lt-cred-mech ON for you, but double-check your configuration.
0: : Config file found: /etc/turn_server_cert.pem
0: : Config file found: /etc/turn_server_pkey.pem
0: : SSL23: Certificate file found: /etc/turn_server_cert.pem
0: : SSL23: Private key file found: /etc/turn_server_pkey.pem
0: : TLS1.0: Certificate file found: /etc/turn_server_cert.pem
0: : TLS1.0: Private key file found: /etc/turn_server_pkey.pem
0: : TLS1.1: Certificate file found: /etc/turn_server_cert.pem
0: : TLS1.1: Private key file found: /etc/turn_server_pkey.pem
0: : TLS1.2: Certificate file found: /etc/turn_server_cert.pem
0: : TLS1.2: Private key file found: /etc/turn_server_pkey.pem
0: : TLS cipher suite: DEFAULT
0: : DTLS: Certificate file found: /etc/turn_server_cert.pem
0: : DTLS: Private key file found: /etc/turn_server_pkey.pem
0: : DTLS1.2: Certificate file found: /etc/turn_server_cert.pem
0: : DTLS1.2: Private key file found: /etc/turn_server_pkey.pem
0: : DTLS cipher suite: DEFAULT
0: : NO EXPLICIT LISTENER ADDRESS(ES) ARE CONFIGURED
0: : ===========Discovering listener addresses: =========
0: : Listener address to use: 127.0.0.1
0: : Listener address to use: 172.26.114.234
0: : Listener address to use: 172.17.0.1
0: : Listener address to use: ::1
0: : =====================================================
0: : Total: 2 'real' addresses discovered
0: : =====================================================
0: : NO EXPLICIT RELAY ADDRESS(ES) ARE CONFIGURED
0: : ===========Discovering relay addresses: =============
0: : Relay address to use: 172.26.114.234
0: : Relay address to use: 172.17.0.1
0: : Relay address to use: ::1
0: : =====================================================
0: : Total: 3 relay addresses discovered
0: : =====================================================
0: : pid file created: /var/run/turnserver.pid
0: : IO method (main listener thread): epoll (with changelist)
0: : WARNING: I cannot support STUN CHANGE_REQUEST functionality because only one IP address is provided
0: : Wait for relay ports initialization...
0: :   relay 172.26.114.234 initialization...
0: :   relay 172.26.114.234 initialization done
0: :   relay 172.17.0.1 initialization...
0: :   relay 172.17.0.1 initialization done
0: :   relay ::1 initialization...
0: :   relay ::1 initialization done
0: : Relay ports initialization done
0: : IO method (general relay thread): epoll (with changelist)
0: : turn server id=0 created
0: : IO method (general relay thread): epoll (with changelist)
0: : turn server id=1 created
0: : Total General servers: 2
0: : IO method (auth thread): epoll (with changelist)
0: : IO method (auth thread): epoll (with changelist)
0: : IO method (admin thread): epoll (with changelist)
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported

**Comment by misi** [comment]
check sctp support of your kernel. Alternatively try to recompile coturn without SCTP

**Comment by sdrhmn** [comment]
How to recompile coturn without sctp?

**Comment by tastytea** [comment]
It looks like `TURN_NO_SCTP=1 ./configure` (followed by `make`) should work. 

https://github.com/coturn/coturn/blob/553ce0216823904d4e52a9629c5bcbed4713f3d2/configure#L1019-L1029

**Comment by sdrhmn** [comment]
These may be a quick fix for you -

I installed coturn on Ubuntu 20 LTS on Google Cloud
    yum install coturn

I enabled /etc/coturn
    TURNSERVER_ENABLED=1

And below is the config in /etc/turnserver.conf
    listening-port=3478
    tls-listening-port=5349
    alt-listening-port=0
    alt-tls-listening-port=0
    listening-ip=10.128.0.29
    relay-ip=10.128.0.29
    external-ip=34.123.173.190
    min-port=49152
    max-port=65535
    verbos
    server-name=bottomup.fit
    user=bottomup:0x6a5c552669f53d72590b0e369ba28402
    realm=bottomup.fit
    cert=/etc/letsencrypt/live/bottomup.fit/fullchain.pem
    pkey=/etc/letsencrypt/live/bottomup.fit/privkey.pem
    syslog
    no-multicast-peers
    cli-password=$5$79a316b350311570$81df9cfb9af7f5e5a76eada31e7097b663a0670f99a3c07ded3f1c8e59c5658a

DNS is set as below
    A    stun    34.123.173.190    600
    A    turn    34.123.173.190    600

Below is the output I get when I run turnserver -c turnserver.conf
0: log file opened: /var/log/turn_5494_2021-07-13.log
0: Listener address to use: 10.128.0.29
0: Relay address to use: 10.128.0.29
0: Config file found: /etc/turnserver.conf
0: 
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.5.1.1 'dan Eider'
0: 
Max number of open files/sockets allowed for this process: 1048576
0: 
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 524000 (approximately)
0: 

==== Show him the instruments, Practical Frost: ====

0: TLS supported
0: DTLS supported
0: DTLS 1.2 supported
0: TURN/STUN ALPN supported
0: Third-party authorization (oAuth) supported
0: GCM (AEAD) supported
0: OpenSSL compile-time version: OpenSSL 1.1.1f  31 Mar 2020 (0x1010106f)
0: 
0: SQLite supported, default database location is /var/lib/turn/turndb
0: Redis supported
0: PostgreSQL supported
0: MySQL supported
0: MongoDB is not supported
0: 
0: Default Net Engine version: 3 (UDP thread per CPU core)

=====================================================

0: Domain name: 
0: Default realm: bottomup.fit
0: SSL23: Certificate file found: /etc/letsencrypt/live/bottomup.fit/fullchain.pem
0: SSL23: Private key file found: /etc/letsencrypt/live/bottomup.fit/privkey.pem
0: ERROR: set_ctx: ERROR: cannot set DH
0: TLS1.0: Certificate file found: /etc/letsencrypt/live/bottomup.fit/fullchain.pem
0: TLS1.0: Private key file found: /etc/letsencrypt/live/bottomup.fit/privkey.pem
0: ERROR: set_ctx: ERROR: cannot set DH
0: TLS1.1: Certificate file found: /etc/letsencrypt/live/bottomup.fit/fullchain.pem
0: TLS1.1: Private key file found: /etc/letsencrypt/live/bottomup.fit/privkey.pem
0: ERROR: set_ctx: ERROR: cannot set DH
0: TLS1.2: Certificate file found: /etc/letsencrypt/live/bottomup.fit/fullchain.pem
0: TLS1.2: Private key file found: /etc/letsencrypt/live/bottomup.fit/privkey.pem
0: ERROR: set_ctx: ERROR: cannot set DH
0: TLS cipher suite: DEFAULT
0: DTLS: Certificate file found: /etc/letsencrypt/live/bottomup.fit/fullchain.pem
0: DTLS: Private key file found: /etc/letsencrypt/live/bottomup.fit/privkey.pem
0: ERROR: set_ctx: ERROR: cannot set DH
0: DTLS1.2: Certificate file found: /etc/letsencrypt/live/bottomup.fit/fullchain.pem
0: DTLS1.2: Private key file found: /etc/letsencrypt/live/bottomup.fit/privkey.pem
0: ERROR: set_ctx: ERROR: cannot set DH
0: DTLS cipher suite: DEFAULT
0: pid file created: /var/run/turnserver.pid
0: IO method (main listener thread): epoll (with changelist)
0: WARNING: I cannot support STUN CHANGE_REQUEST functionality because only one IP address is provided
0: Wait for relay ports initialization...
0:   relay 10.128.0.29 initialization...
0:   relay 10.128.0.29 initialization done
0: Relay ports initialization done
0: IO method (general relay thread): epoll (with changelist)
0: turn server id=1 created
0: IPv4. TLS/SCTP listener opened on : 10.128.0.29:3478
0: IPv4. TLS/TCP listener opened on : 10.128.0.29:3478
0: IPv4. TLS/SCTP listener opened on : 10.128.0.29:5349
0: IPv4. TLS/TCP listener opened on : 10.128.0.29:5349
0: IO method (general relay thread): epoll (with changelist)
0: turn server id=0 created
0: IPv4. DTLS/UDP listener opened on: 10.128.0.29:3478
0: IPv4. DTLS/UDP listener opened on: 10.128.0.29:5349
0: Total General servers: 2
0: IO method (auth thread): epoll (with changelist)
0: IPv4. TLS/SCTP listener opened on : 10.128.0.29:3478
0: IPv4. TLS/TCP listener opened on : 10.128.0.29:3478
0: SQLite DB connection success: /var/lib/turn/turndb
0: IPv4. TLS/SCTP listener opened on : 10.128.0.29:5349
0: IPv4. TLS/TCP listener opened on : 10.128.0.29:5349
0: IO method (auth thread): epoll (with changelist)
0: IO method (admin thread): epoll (with changelist)
0: IPv4. CLI listener opened on : 127.0.0.1:5766

But the TRICKLE ICE test fails

Hope its easy for you!

**Comment by eakraly** [comment]
Duplicate in #492
Resolved in #1016
