### ISSUE TITLE
Authentication failed when coturn is behind the udp load balancer like nginx

### ISSUE THREAD

**Issue by yildirayyilmaz** [coturn/coturn#90]
Hi,

It may be a really simple question because i am a newbie about turn servers. I would like to run coturn server behind a load balancer such as nginx. 
My case is:
1. I have a nginx load balancer on server which is 192.168.1.10. And listening port 3478 for requests. Also this server has public ip address such as 82.222.*.*   
2. I have a turn server (coturn) which is 192.168.1.11. And runing on port 3478 (this server is in the same network with load balancer)
3. I'm testing my turn server connectivity with this site: https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

My problem is:
If i do nat port forwarding from my public ip address to coturn server without using load balancer, connectivity test is performing successfully. However, if i use nginx udp load balancing method for redirecting request to my turn server, connectivity test is returning "Authentication Failed" error. 

Is there any idea about this issue? Any help about this issue is appreciated. 

Thanks,
Yildiray Yilmaz

**Comment by mom040267** [comment]
Any third party load balancer servers are not supported.

**Comment by yildirayyilmaz** [comment]
Thanks for your response. Please forgive me but I need to clarify your response to understand it correctly. Do you mean "you don't give information about third party load balancers in this web site" or "it's not possible to use third party load balancers with coturn"?

Thanks,
Yildiray

**Comment by mom040267** [comment]
Rather the second one. If you read the TURN specs, you will see that it was
designed in the way that make third-party load-balancing a very difficult
thing. Read the section about load balancing in the project web page docs.

**Comment by jinyuxiaoqiang** [comment]
@yildirayyilmaz   I'm now config nginx before coTurn  turn server,  but it can not work . can you show me your nginx udp load balancing config, I will try.

Thanks.

**Comment by yildirayyilmaz** [comment]
Hi @jinyuxiaoqiang ,

I did not use third party load balancers such as nginx for my coturn instances in my enviorment. Coturn already has load balancing mechanism and it is really sufficient.

**Comment by jinyuxiaoqiang** [comment]
Thanks for your reply.
As you had said bellow, if i had made a mistoken?
> Hi,

It may be a really simple question because i am a newbie about turn servers. I would like to run coturn server behind a load balancer such as nginx.
My case is:

I have a nginx load balancer on server which is 192.168.1.10. And listening port 3478 for requests. Also this server has public ip address such as 82.222..
I have a turn server (coturn) which is 192.168.1.11. And runing on port 3478 (this server is in the same network with load balancer)
I'm testing my turn server connectivity with this site: https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
My problem is:
If i do nat port forwarding from my public ip address to coturn server without using load balancer, connectivity test is performing successfully. However, if i use nginx udp load balancing method for redirecting request to my turn server, connectivity test is returning "Authentication Failed" error.

Is there any idea about this issue? Any help about this issue is appreciated.

**Comment by yildirayyilmaz** [comment]
@jinyuxiaoqiang it was my problem case. After @mom040267 's answers i focused on coturn's load balancing mechanism.

**Comment by gatici** [comment]
Hello, I are trying to  use coturn server  which  is  located behind a  external load balancer  and  coturn  server also  has  local and  public  ip's. I am getting several  type of errors.  Is this  configration  correct  or  possible ?  should coturn located  front  of  load balancer   ?

**Comment by eakraly** [comment]
No updates in 5 years. Closing.
