### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by korayvt** [coturn/coturn#915]
Hello to everyone,

For a long time PRs are waiting to be merged and there are many issues waiting for answers or comments.

There are many people who use coturn in their architecture and they try to contribute, give feedback, report bugs.

I mean the user community is active but the project management has been inactive for almost a year.

Is this project dead?

**Comment by tyranron** [comment]
@korayvt hello 👋

Seems like @misi doesn't have enough bandwith to actively maintain the project. He gave me access to the project for maintaining its Docker image, and I'm doing my best in it. However, I have no comptence to maintain and guide other parts of the project (at least, because I nave no experience with C), so I cannot help with those issues and PRs. And I haven't seen any other active maintainers.

From my prespective it would be nice to throw a contributor call, so a new maintainers team may be created, chosen by @misi.

**Comment by mom040267** [comment]
I am the original developer and maintainer but I passed the torch to Misi and I really do not have bandwidth myself. I d love to see the project going forward so I support the idea choosing a new team if Misi is busy.

Oleg

**Comment by jacereda** [comment]
[Epic Games](https://github.com/EpicGames) is depending on this project for their Pixel Streaming feature in Unreal Engine. Maybe they should be aware of the current status, in case they want to take action in any way that can help the project.

**Comment by misi** [comment]
Yes it is right and I am so sorry about it. It is a shame, but actually I don't find the time to work on coturn. :(   
I am going to add all my support to @tyranron and today added Gustavo Gracia to the maintainer team. 
I do my best to make a smooth handover to them. And it would be great to have any other helping hand. Please reach me out if you want to involve and contribute to the project.

**Comment by saghul** [comment]
No need to be sorry. Thank you so much for your work here!

**Comment by ggarber** [comment]
Thank you everybody for raising this issue, I hope we can maintain and keep improving coturn together.     

THANK YOU MISI FOR ALL THE WORK!
