### ISSUE TITLE
Building coturn on macOS

### ISSUE THREAD

**Issue by eakraly** [coturn/coturn#946]
Now that there are 2 mechanisms to build coturn (configure and cmake) I have following:
- configure works perfectly (provided I pass --prefix=/usr/local/opt/openssl@1.1 where openssl@1.1 is from brew)
- CMake is struggling with all the dependencies (openssl, hires, mongo-c, etc), but since only openssl is required then `-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1/` fixes it
- CMake build does not pass because of missing `pthread_barrier_t` `pthread_barrier_wait` `pthread_barrier_init` - what is the solution to that?

@jeremy-murphy you submitted a great improvement to CMake build lately so you can probably shed some more light on building coturn using CMake on macOS?

**Comment by jeremy-murphy** [comment]
Hi @eakraly , thanks for the compliment.

If a dependency is optional, you may add the `QUIET` option to `find_package` to prevent the noisy warning when it is not found. Then you can optionally print whatever message you like or just summarize at the end. KDE packages do something like that, since they have a lot of optional dependencies.

Yes, we have to use `-DTURN_NO_THREAD_BARRIERS` to compile, either passed via an environment variable such as `CFLAGS` or due to a limitation in our packaging system, we modified the root cmake with:
```
if (APPLE)
	add_compile_definitions("TURN_NO_THREAD_BARRIERS")
endif()
```
It's interesting that the configure mechanism works without that manual intervention. I thought it must be checking for `_POSIX_BARRIERS` and enabling `TURN_NO_THREAD_BARRIERS` if required but I can't see any evidence of that.

One pragmatic solution is to put some code like this at the top of `netengine.c` or in a header file:
```
#if !defined(_POSIX_BARRIERS) || _POSIX_BARRIERS <= 0
#define TURN_NO_THREAD_BARRIERS
#endif
```
Presumably you can find a cleaner way to adopt that. It would be best done at the CMake level, but I'm not sure how.
Reference document: https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap02.html#tag_02_01_06
