### ISSUE TITLE
Cleanup SSL renegotiation related code

### ISSUE THREAD

**Issue by eakraly** [coturn/coturn#952]
Code wrapped with `SSL3_FLAGS_NO_RENEGOTIATE_CIPHERS` can be removed now that renegotiation is completely disabled in #942

**Comment by steffen-moser** [comment]
Unfortunately, #942 is another show stopper of compiling coturn with OpenSSL 1.0.2ze on Solaris 11.4 SRU 48. #129 

SSL_OP_NO_RENEGOTIATION does only seem to be defined in OpenSSL 1.1 or newer. 

Just disabling it with a #ifdefined statement similar to the 'replace_one_ssl_ctx' problem we discussed in #795 allows compilation in Solaris 11.4, but I am not sure about the security implications, yet. Especially, if we removed the SSL3_FLAGS_NO_RENEGOTIATE_CIPHERS, I see a regression under security aspects. 

My question is: Is it possible to deactivate renegotiation completely in OpenSSL 1.0.x as SSL_OP_NO_RENEGOTIATION does this for OpenSSL 1.1.x and above?

**Comment by steffen-moser** [comment]
After doing some tests (with omitted #942 in order to get OpenSSL 1.0.2 compatibility), it seems that the code wrapped with SSL3_FLAGS_NO_RENEGOTIATE_CIPHERS successfully stops the RENEGOTIATION after three attempts for TLS as defined in SSL_MAX_RENEG_NUMBER. 

(Maybe, lowering the number to 1 could make coturn less vulnerable to SSL renegotiation attacks). 

The question is: Is it worth to implement this ssl_info_callback() function also for DTLS? Currently, with omitted #942, DTLS seems to allow an arbitrary amount of RENEGOTIATION attempts. If so, we could implement another SSL version check. For 1.1.x and above, we use #942, and for 1.0.x, we use the ssl_info_callback() together with the hack SSL3_FLAGS_NO_RENEGOTIATE_CIPHERS.

I completely agree about the fact that supporting these old OpenSSL versions is really a nightmare and a project cannot do this forever. Unfortunately, there are still operating systems which rely on this old version as a default, mainly because of the missing FIPS 140-2 mode in OpenSSL 1.1.x. At least, there is hope that OpenSSL 3 might get a FIPS-140 validation.

**Comment by eakraly** [comment]
Thank you @steffen-moser !
Can you please submit a PR for your changes so we can discuss the actual code?

TBH using openssl-1.0.2 is a security risk on its own (this version has been out of support for a long time) though in context of TURN this is not a big issue.

And I'm sure we will find a way to disable renegotiation in a nice way - without keeping old code (that I would be happy to remove)

**Comment by robert-scheck** [comment]
CentOS/RHEL 7 still ships OpenSSL 1.0.2 (including security fixes until at least mid of 2024).
